run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - docs
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gofmt
    - goimports
    - deadcode
    - unused
    - revive
    - ineffassign
    - unparam
    - prealloc
    - misspell
    - gosec
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
  misspell:
    locale: US
  gosec:
    exclude:
      - G104
